version: "3.9"

services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chatapp_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./ChatApp-Backend

      dockerfile: Dockerfile
    container_name: ChatApp-Backend
    depends_on:
      mysql-container:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/chatapp_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

    restart: on-failure

  frontend:
    build:
      context: ./chatapp-frontend
      dockerfile: Dockerfile
      
    container_name: chatapp-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: on-failure

volumes:
  mysql_data:

